version: "3.7"

services:
  postgres:
    image: postgres:14
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    networks:
      monitor-net:
        ipv4_address: 192.168.240.2

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: pg-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin123@pg-db:5432/demo?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      monitor-net:
        ipv4_address: 192.168.240.3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      monitor-net:
        ipv4_address: 192.168.240.4

networks:
  monitor-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/24
