version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - monitor-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-net
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loadgen:
    build: ./loadgen
    container_name: loadgen
    ports:
      - "8000:8000"
    networks:
      - monitor-net
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:

networks:
  monitor-net:
    driver: bridge
