scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped>
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seco>
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']
- job_name: 'postgres'
    static_configs:
      - targets: ['192.168.134.196:9187']
  - job_name: 'my_post'
    static_configs:
      - targets: ['localhost:9187']

